name: Update ZIP to REPO

on:
  repository_dispatch:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - 'startupdate'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Download
        run: |
          curl -L -o xray-linux-mips.zip "https://github.com/lunatickochiya/openwrt-xray/releases/latest/download/xray-linux-mips.zip"
          curl -L -o xray-linux-mipsle.zip "https://github.com/lunatickochiya/openwrt-xray/releases/latest/download/xray-linux-mipsle.zip"

      - name: push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -am "update mips, mipsle $(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push -v --progress